apiVersion: v1
kind: Service
metadata:
  name: java-demoapp-service
spec:
  type: LoadBalancer
  selector:
    app: java-demoapp
  ports:
    - name: tcp
      protocol: TCP
      port: 8080
      targetPort: 8080